export const LOCATION_STATE_OPTIONS = ["Maharashtra"] as const;

export const MAHARASHTRA_CITIES = [
  "Ahmednagar",
  "Akola",
  "Alibag",
  "Amravati",
  "Aurangabad",
  "Baramati",
  "Beed",
  "Bhandara",
  "Bhiwandi",
  "Bhusawal",
  "Boisar",
  "Chandrapur",
  "Dhule",
  "Gadchiroli",
  "Gondia",
  "Hinganghat",
  "Hingoli",
  "Ichalkaranji",
  "Jalgaon",
  "Jalna",
  "Karad",
  "Khamgaon",
  "Kolhapur",
  "Latur",
  "Malegaon",
  "Mira-Bhayandar",
  "Mumbai",
  "Nagpur",
  "Nanded",
  "Nandurbar",
  "Nashik",
  "Navi Mumbai",
  "Osmanabad",
  "Palghar",
  "Panvel",
  "Parbhani",
  "Pimpri-Chinchwad",
  "Pune",
  "Raigad",
  "Ratnagiri",
  "Sangamner",
  "Sangli",
  "Satara",
  "Sindhudurg",
  "Solapur",
  "Thane",
  "Ulhasnagar",
  "Wardha",
  "Washim",
  "Yavatmal",
] as const;

export const CITY_OPTIONS_BY_STATE: Record<string, readonly string[]> = {
  Maharashtra: MAHARASHTRA_CITIES,
};
