export const LOCATION_STATE_OPTIONS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export const CITY_OPTIONS_BY_STATE: Record<string, readonly string[]> = {
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Car Nicobar",
    "Diglipur",
    "Havelock Island",
    "Little Andaman",
    "Mayabunder",
    "Rangat",
    "Campbell Bay",
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kadapa",
    "Rajahmundry",
    "Tirupati",
    "Anantapur",
    "Chittoor",
    "Eluru",
    "Srikakulam",
    "Vizianagaram",
    "Ongole",
    "Machilipatnam",
    "Tenali",
    "Nandyal",
    "Bhimavaram",
    "Amaravati",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Tawang",
    "Pasighat",
    "Ziro",
    "Bomdila",
    "Roing",
    "Tezu",
    "Namsai",
    "Aalo",
    "Khonsa",
    "Seppa",
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Tezpur",
    "Nagaon",
    "Tinsukia",
    "Sivasagar",
    "Dhemaji",
    "Bongaigaon",
    "Karimganj",
    "Goalpara",
    "Dhubri",
    "Barpeta",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Bihar Sharif",
    "Siwan",
    "Motihari",
    "Sasaram",
    "Samastipur",
  ],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Durg",
    "Bilaspur",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Rajnandgaon",
    "Dhamtari",
    "Mahasamund",
    "Janjgir",
    "Kanker",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Dadra",
    "Naroli",
  ],
  Delhi: [
    "New Delhi",
    "Central Delhi",
    "East Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Canacona",
    "Valpoi",
    "Sanguem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Anand",
    "Nadiad",
    "Bharuch",
    "Navsari",
    "Valsad",
    "Mehsana",
    "Patan",
    "Gandhinagar",
    "Morbi",
    "Porbandar",
    "Godhra",
  ],
  Haryana: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Bhiwani",
    "Sirsa",
    "Jhajjar",
    "Rewari",
    "Narnaul",
    "Kurukshetra",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Mandi",
    "Solan",
    "Kullu",
    "Hamirpur",
    "Bilaspur",
    "Una",
    "Chamba",
    "Nahan",
    "Palampur",
    "Kangra",
    "Baddi",
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Pulwama",
    "Kupwara",
    "Udhampur",
    "Kathua",
    "Poonch",
    "Sopore",
    "Budgam",
    "Kulgam",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Dumka",
    "Palamu",
    "Godda",
    "Sahibganj",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Dharwad",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Davanagere",
    "Bidar",
    "Raichur",
    "Hassan",
    "Mandya",
    "Chikkamagaluru",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Kottayam",
    "Kannur",
    "Palakkad",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Kasaragod",
    "Wayanad",
  ],
  Ladakh: ["Leh", "Kargil", "Nubra", "Diskit", "Zanskar"],
  Lakshadweep: ["Kavaratti", "Agatti", "Amini", "Andrott", "Minicoy"],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Satna",
    "Rewa",
    "Ratlam",
    "Katni",
    "Dewas",
    "Vidisha",
    "Chhindwara",
    "Shivpuri",
    "Sehore",
    "Mandsaur",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Alibag",
    "Amravati",
    "Aurangabad",
    "Baramati",
    "Beed",
    "Bhandara",
    "Bhiwandi",
    "Bhusawal",
    "Boisar",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hinganghat",
    "Hingoli",
    "Ichalkaranji",
    "Jalgaon",
    "Jalna",
    "Karad",
    "Khamgaon",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mira-Bhayandar",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Navi Mumbai",
    "Osmanabad",
    "Palghar",
    "Panvel",
    "Parbhani",
    "Pimpri-Chinchwad",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangamner",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Ulhasnagar",
    "Wardha",
    "Washim",
    "Yavatmal",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Ukhrul",
    "Senapati",
    "Kakching",
    "Tamenglong",
    "Jiribam",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongstoin",
    "Baghmara",
    "Williamnagar",
    "Nongpoh",
    "Mawkyrwat",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Saiha",
    "Mamit",
    "Lawngtlai",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek",
    "Mon",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jeypore",
    "Jharsuguda",
    "Angul",
    "Dhenkanal",
    "Rayagada",
    "Keonjhar",
  ],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam", "Villianur"],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Firozpur",
    "Abohar",
    "Kapurthala",
    "Sangrur",
    "Barnala",
    "Rupnagar",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Udaipur",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Sri Ganganagar",
    "Bhilwara",
    "Chittorgarh",
    "Tonk",
    "Nagaur",
    "Barmer",
  ],
  Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Singtam", "Rangpo"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Nagercoil",
    "Kanchipuram",
    "Kumbakonam",
    "Hosur",
    "Karur",
    "Namakkal",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Siddipet",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Khowai",
    "Ambassa",
    "Sonamura",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Mathura",
    "Jhansi",
    "Ayodhya",
    "Firozabad",
    "Muzaffarnagar",
    "Basti",
    "Ballia",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Nainital",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Pithoragarh",
    "Almora",
    "Pauri",
    "Tehri",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Kharagpur",
    "Bardhaman",
    "Malda",
    "Darjeeling",
    "Krishnanagar",
    "Midnapore",
    "Jalpaiguri",
    "Berhampore",
    "Haldia",
    "Raiganj",
    "Cooch Behar",
  ],
};
